= Git Versioner Maven Extension Examples

This repository holds examples demonstrating use of https://github.com/manikmagar/git-versioner-maven-extension[git-versioner-maven-extension].

Extension is configured in `.mvn` directories in each example project.

To run commands against all projects, use `./mvn-delegate.sh` script at the root.


.Print project version for all example projects
[source,shell]
----
./mvn-delegate.sh help:evaluate -Dexpression=project.version -q -DforceStdout

Running 'help:evaluate -Dexpression=project.version -q -DforceStdout' for simple-project
0.0.0-1
################################
Running 'help:evaluate -Dexpression=project.version -q -DforceStdout' for simple-project-props
1.3.4+92bbdaa
################################
Running 'help:evaluate -Dexpression=project.version -q -DforceStdout' for parent-child-project
0.0.0-1
################################
Running 'help:evaluate -Dexpression=project.version -q -DforceStdout' for multi-module-project
0.0.0-1
################################
----

.Clean all projects
[source,shell]
----
./mvn-delegate.sh -q clean
----

== Increment versions

Run any of the below commands. For each version increment command below, one commit per sample project is added to local git repository.

NOTE: `simple-project-props` overrides version keywords in link:simple-project-props/.mvn/git-versioner.extensions.properties[git-versioner.extensions.properties]. Version commits will add commits with those keywords.

.Check current version
[source,shell]
----
./mvn-delegate.sh help:evaluate -Dexpression=project.version -q -DforceStdout
----


.Increment patch version
[source,shell]
----
./mvn-delegate.sh -q git-versioner:commit-patch
----

.Check new version
[source,shell]
----
./mvn-delegate.sh help:evaluate -Dexpression=project.version -q -DforceStdout
----


.Increment minor version
[source,shell]
----
./mvn-delegate.sh -q git-versioner:commit-minor
----


.Check new version
[source,shell]
----
./mvn-delegate.sh help:evaluate -Dexpression=project.version -q -DforceStdout
----


.Increment major version
[source,shell]
----
./mvn-delegate.sh -q git-versioner:commit-major
----


.Check new version
[source,shell]
----
./mvn-delegate.sh help:evaluate -Dexpression=project.version -q -DforceStdout
----

